/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cargo: typeof import('./src/components/Cargo.vue')['default']
    Cargos: typeof import('./src/components/Cargos.vue')['default']
    EditElement: typeof import('./src/components/mapEdit/EditElement.vue')['default']
    EditElementView: typeof import('./src/components/mapEdit/EditElementView.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Floor: typeof import('./src/components/Floor.vue')['default']
    Keeper: typeof import('./src/components/mapEdit/Keeper.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MapBlock: typeof import('./src/components/mapEdit/MapBlock.vue')['default']
    MapDataDisplay: typeof import('./src/components/mapEdit/MapDataDisplay.vue')['default']
    PlacePoint: typeof import('./src/components/PlacePoint.vue')['default']
    PlacePoints: typeof import('./src/components/PlacePoints.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Target: typeof import('./src/components/target.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Wall: typeof import('./src/components/Wall.vue')['default']
  }
}
